version: 2.1
jobs:
  lint-theme:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    environment:
      - THEME_PATH: "vendor/snowdog/theme-frontend-alpaca"
      - CONFIG_PATH: "vendor/snowdog/theme-frontend-alpaca/.circleci/frontools/config"
    steps:
      - run: sudo apt-get install rsync
      - checkout
      - run: mkdir -p $THEME_PATH
      - run: rsync -r --delete . $THEME_PATH
      - run: cp "$THEME_PATH/composer.json" .
      - run: composer update --no-dev --no-interaction --prefer-dist --no-progress --ignore-platform-reqs
      - run: mkdir -p dev/tools/frontools
      - run: cp -r $CONFIG_PATH dev/tools/frontools
      - run: cd vendor/snowdog/frontools && yarn && yarn setup
      - run: cd tools && yarn inheritance
      - run: cd tools && yarn sasslint --ci
      - run: cd tools && yarn styles --ci --pipeline
      - run: cd tools && yarn csslint --ci
  deploy-components:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    environment:
      - NOW_SCOPE: "snowdog"
      - NOW_PROJECT: "alpaca-components-2"
      - GIT_BRANCH: "This is pipeline git branch << pipeline.git.branch >>"
      - NOW_URL: "https://${NOW_PROJECT}-${CIRCLE_BRANCH}.now.sh"
    steps:
      - checkout
      - run: cd Snowdog_Components && yarn
      - run: cd Snowdog_Components && yarn build --ci
      - run: cd Snowdog_Components && sudo npm install --global --unsafe-perm --silent now@16.7
      - run: echo $CIRCLE_BRANCH
      - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        now --token $NOW_TOKEN --local-config .now/now.prod.json
                        now --token $NOW_TOKEN --local-config .now/now.prod.json alias
                    elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                        now --token $NOW_TOKEN --local-config .now/now.stage.json
                        now --token $NOW_TOKEN --local-config .now/now.stage.json alias
                    else
                        ./.now/now.feature.sh
                        now --token $NOW_TOKEN --local-config .now/now.feature.json
                        now --token $NOW_TOKEN --local-config .now/now.feature.json alias
                    fi

workflows:
  theme:
    jobs:
      - lint-theme
  components:
    jobs:
      - deploy-components
